# Homie reasoning node — headless, hardened, dual-boot NixOS.
#
# Device-specific values are marked <PLACEHOLDER>; fill them in before install.
# Imported by flake.nix together with the machine-specific
# hardware-configuration.nix produced by `nixos-generate-config`.

{ config, lib, pkgs, ... }:

{
  # hardware-configuration.nix is generated by `nixos-generate-config` and sits
  # beside this file in /etc/nixos/ at install time (see os/INSTALL.md).
  imports = [ ./hardware-configuration.nix ./nvidia-cuda.nix ];

  # ---------------------------------------------------------------------------
  # Bootloader: GRUB (EFI) + os-prober for dual-boot.
  #
  # Why GRUB+os-prober rather than systemd-boot: systemd-boot has no equivalent
  # of os-prober and will NOT auto-discover an existing Windows/Linux install.
  # GRUB's os-prober scans other partitions, finds the existing OS, and writes a
  # chainload entry automatically — exactly the dual-boot requirement. GRUB is
  # installed into a subdirectory of the (possibly shared) ESP, leaving existing
  # entries intact.
  # ---------------------------------------------------------------------------
  boot.loader.systemd-boot.enable = false;
  boot.loader.efi.canTouchEfiVariables = true;
  boot.loader.efi.efiSysMountPoint = "/boot"; # must match where the ESP is mounted

  boot.loader.grub = {
    enable = true;
    efiSupport = true;
    device = "nodev"; # EFI install; GRUB is not embedded in an MBR
    useOSProber = true; # discover & chainload the existing OS
    configurationLimit = 20; # keep generations for rollback at the menu
  };

  # ---------------------------------------------------------------------------
  # Full-disk encryption: unlock the LUKS root in the initrd.
  # <LUKS_UUID> = `blkid -s UUID -o value /dev/<ROOT>` (the RAW partition's UUID,
  # not the opened mapper). The mapper name "cryptroot" must match what
  # hardware-configuration.nix mounts as /.
  # ---------------------------------------------------------------------------
  boot.initrd.luks.devices."cryptroot" = {
    device = "/dev/disk/by-uuid/<LUKS_UUID>";
    allowDiscards = true; # enable only if root is on an SSD/NVMe
  };

  # ---------------------------------------------------------------------------
  # Headless / text-first: no X, no Wayland, no display manager. Console only.
  # ---------------------------------------------------------------------------
  services.xserver.enable = false;
  documentation.enable = false;

  # Quiet console: boot straight in, autologin homie on tty1.
  boot.consoleLogLevel = 3;
  boot.kernelParams = [ "quiet" "loglevel=3" ];

  services.getty = {
    autologinUser = "homie";
    greetingLine = ""; # no version/issue banner
    helpLine = "";
  };

  # ---------------------------------------------------------------------------
  # Users. mutableUsers=false makes the config the source of truth (no drift).
  # Provide a hashedPassword for both accounts:  mkpasswd -m yescrypt
  # ---------------------------------------------------------------------------
  users.mutableUsers = false;

  users.users.homie = {
    isNormalUser = true;
    description = "Homie";
    hashedPassword = "<HOMIE_PASSWORD_HASH>"; # mkpasswd -m yescrypt
    extraGroups = [ "video" ]; # camera-frame rendering to the console
  };

  users.users.root.hashedPassword = "<ROOT_PASSWORD_HASH>"; # rescue account

  # ---------------------------------------------------------------------------
  # The Homie daemon: bus + Remember + Supervisor via the Python entrypoint.
  # Repo lives at /opt/homie; entrypoint is /opt/homie/scripts/run.py.
  # ---------------------------------------------------------------------------
  # python311 runs the daemon; git is the update channel (the box is a git checkout of the
  # repo, updated via scripts/update.py — pull + health-check + restart). See os/INSTALL.md.
  environment.systemPackages = [ pkgs.python311 pkgs.git ];

  systemd.services.homie = {
    description = "Homie reasoning node (bus + Remember + Supervisor)";
    wantedBy = [ "multi-user.target" ];
    after = [ "network.target" "local-fs.target" ];

    # Crash-loop ceiling (Charter 27a): if it restarts >5 times in 5 min, STOP and surface the
    # fault to the owner rather than thrashing silently. A box that restart-loops forever is
    # hiding a problem — that's the opposite of self-healed.
    startLimitIntervalSec = 300;
    startLimitBurst = 5;

    serviceConfig = {
      ExecStart = "${pkgs.python311}/bin/python3 /opt/homie/scripts/run.py";
      # Liveness watchdog (Charter 27a): the daemon proves it's alive with sd_notify; if it
      # wedges (hung but not crashed), systemd kills + restarts it. Type=notify lets it send
      # READY=1 on boot and WATCHDOG=1 on the heartbeat (core/watchdog.py).
      Type = "notify";
      WatchdogSec = "60s";
      NotifyAccess = "main";
      WorkingDirectory = "/opt/homie";
      Environment = [
        "HOMIE_STATE=/var/lib/homie"
        # Pin the home's timezone so Remember's hour-of-day buckets and the tiles all
        # agree on "what hour is it" (second-review N7). Change this on a move.
        "HOMIE_TZ=Europe/Berlin"
        # Set the home's coordinates to enable latitude-correct solar dusk for lighting
        # (second-review N4); leave unset for the fixed 18:00–07:00 fallback. Fill in on
        # move-in (e.g. Kiel: 54.32, 10.14).
        # "HOMIE_LAT=54.32"
        # "HOMIE_LON=10.14"
        # Point Homie at Home Assistant to drive REAL lights (DIRIGERA/Tradfri) and hear
        # human switch-flips. Both must be set or Homie stays on the no-actuation stub.
        # The token: HA → your profile → Security → Long-lived access tokens. Prefer
        # delivering it out-of-band (see the LoadCredential note below) over hard-coding.
        # "HOMIE_HOME_URL=ws://mini-pc.local:8123/api/websocket"
        # "HOMIE_HOME_TOKEN=<long-lived-access-token>"
      ];
      User = "homie";
      Group = "users";

      # Self-healing at the service layer: always come back up.
      Restart = "always";
      RestartSec = 3;

      # Sandboxing / hardening for the daemon.
      NoNewPrivileges = true;
      ProtectSystem = "strict";
      ProtectHome = true;
      PrivateTmp = true;
      ProtectKernelTunables = true;
      ProtectKernelModules = true;
      ProtectControlGroups = true;
      RestrictNamespaces = true;
      RestrictRealtime = true;
      LockPersonality = true;
      SystemCallArchitectures = "native";
      StateDirectory = "homie"; # -> /var/lib/homie (writable: the event log)
    };
  };

  # ---------------------------------------------------------------------------
  # Nightly self-upgrade (Charter 28/28a): pull → run the full suite as a health
  # gate → auto-rollback if unsafe → hold any authority change for the owner →
  # restart onto the new code → append the changelog. Runs on the always-on node.
  # ---------------------------------------------------------------------------
  systemd.services.homie-nightly = {
    description = "Homie nightly self-upgrade (pull, health-gate, rollback, restart)";
    after = [ "network-online.target" ];
    wants = [ "network-online.target" ];
    path = [ pkgs.git ];
    serviceConfig = {
      Type = "oneshot";
      WorkingDirectory = "/opt/homie";
      # --auto: roll back to last-good if the pulled code fails the suite; --restart: apply a
      # healthy, non-authority update. Needs root to git-pull and restart the service.
      ExecStart = "${pkgs.python311}/bin/python3 /opt/homie/scripts/update.py --auto --restart";
    };
  };

  systemd.timers.homie-nightly = {
    description = "Run Homie's nightly self-upgrade at 04:00 (Persistent: catches a missed boot)";
    wantedBy = [ "timers.target" ];
    timerConfig = {
      OnCalendar = "*-*-* 04:00:00";
      Persistent = true;
      RandomizedDelaySec = "600";
    };
  };

  # ---------------------------------------------------------------------------
  # Networking & hardening: firewall on; SSH off by default (opt-in).
  # ---------------------------------------------------------------------------
  networking.hostName = "homie"; # matches the flake attr
  networking.firewall.enable = true;
  networking.firewall.allowPing = false;

  services.openssh = {
    enable = false; # flip to true + add an authorized key for maintenance
    settings = {
      PasswordAuthentication = false;
      PermitRootLogin = "no";
      KbdInteractiveAuthentication = false;
    };
  };

  # No telemetry / no accounts / no cloud. Nothing reports usage at runtime.

  time.timeZone = "<TIMEZONE>"; # e.g. "Europe/Berlin"
  i18n.defaultLocale = "en_US.UTF-8";
  console.keyMap = "<KEYMAP>"; # e.g. "us" or "de"

  # The NixOS release you installed against. Do NOT bump casually.
  system.stateVersion = "<NIXOS_RELEASE>"; # e.g. "24.11"
}
